const DUMMY_DATA = [
  {
    name: "dummy5",
    status: "hosted",
    thumbnailBgColor: "#898989",
    thumbnailTextColor: "#ffffff",
    title: "dummy1",
  },
  {
    name: "dummy5",
    status: "hosted",
    thumbnailBgColor: "#898989",
    thumbnailTextColor: "#ffffff",
    title: "dummy2",
  },
  {
    name: "dummy5",
    status: "hosted",
    thumbnailBgColor: "#898989",
    thumbnailTextColor: "#ffffff",
    title: "dummy3",
  },
  {
    name: "dummy5",
    status: "hosted",
    thumbnailBgColor: "#898989",
    thumbnailTextColor: "#ffffff",
    title: "dummy4",
  },
  {
    name: "dummy5",
    status: "hosted",
    thumbnailBgColor: "#898989",
    thumbnailTextColor: "#ffffff",
    title: "dummy5",
  },
  {
    name: "dummy5",
    status: "hosted",
    thumbnailBgColor: "#898989",
    thumbnailTextColor: "#ffffff",
    title: "dummy6",
  },
  {
    name: "dummy5",
    status: "hosted",
    thumbnailBgColor: "#898989",
    thumbnailTextColor: "#ffffff",
    title: "dummy7",
  },
  {
    name: "dummy5",
    status: "hosted",
    thumbnailBgColor: "#898989",
    thumbnailTextColor: "#ffffff",
    title: "dummy8",
  },
  {
    name: "dummy5",
    status: "hosted",
    thumbnailBgColor: "#898989",
    thumbnailTextColor: "#ffffff",
    title: "dummy9",
  },
  {
    name: "dummy5",
    status: "hosted",
    thumbnailBgColor: "#898989",
    thumbnailTextColor: "#ffffff",
    title: "dummy10",
  },
  {
    name: "dummy5",
    status: "hosted",
    thumbnailBgColor: "#898989",
    thumbnailTextColor: "#ffffff",
    title: "dummy11",
  },
  {
    name: "dummy5",
    status: "hosted",
    thumbnailBgColor: "#898989",
    thumbnailTextColor: "#ffffff",
    title: "dummy12",
  },
  {
    name: "dummy5",
    status: "hosted",
    thumbnailBgColor: "#898989",
    thumbnailTextColor: "#ffffff",
    title: "dummy13",
  },
  {
    name: "dummy5",
    status: "hosted",
    thumbnailBgColor: "#898989",
    thumbnailTextColor: "#ffffff",
    title: "dummy14",
  },
  {
    name: "dummy5",
    status: "hosted",
    thumbnailBgColor: "#898989",
    thumbnailTextColor: "#ffffff",
    title: "dummy15",
  },
  {
    name: "dummy5",
    status: "hosted",
    thumbnailBgColor: "#898989",
    thumbnailTextColor: "#ffffff",
    title: "dummy16",
  },
  {
    name: "dummy5",
    status: "hosted",
    thumbnailBgColor: "#898989",
    thumbnailTextColor: "#ffffff",
    title: "dummy17",
  },
  {
    name: "dummy5",
    status: "hosted",
    thumbnailBgColor: "#898989",
    thumbnailTextColor: "#ffffff",
    title: "dummy18",
  },
  {
    name: "dummy5",
    status: "hosted",
    thumbnailBgColor: "#898989",
    thumbnailTextColor: "#ffffff",
    title: "dummy19",
  },
  {
    name: "dummy5",
    status: "hosted",
    thumbnailBgColor: "#898989",
    thumbnailTextColor: "#ffffff",
    title: "dummy20",
  },
  {
    name: "dummy5",
    status: "hosted",
    thumbnailBgColor: "#898989",
    thumbnailTextColor: "#ffffff",
    title: "dummy21",
  },
  {
    name: "dummy5",
    status: "hosted",
    thumbnailBgColor: "#898989",
    thumbnailTextColor: "#ffffff",
    title: "dummy22",
  },
  {
    name: "dummy5",
    status: "hosted",
    thumbnailBgColor: "#898989",
    thumbnailTextColor: "#ffffff",
    title: "dummy23",
  },
  {
    name: "dummy5",
    status: "hosted",
    thumbnailBgColor: "#898989",
    thumbnailTextColor: "#ffffff",
    title: "dummy24",
  },
  {
    name: "dummy5",
    status: "hosted",
    thumbnailBgColor: "#898989",
    thumbnailTextColor: "#ffffff",
    title: "dummy25",
  },
  {
    name: "dummy5",
    status: "hosted",
    thumbnailBgColor: "#898989",
    thumbnailTextColor: "#ffffff",
    title: "dummy26",
  },
  {
    name: "dummy5",
    status: "hosted",
    thumbnailBgColor: "#898989",
    thumbnailTextColor: "#ffffff",
    title: "dummy27",
  },
  {
    name: "dummy5",
    status: "hosted",
    thumbnailBgColor: "#898989",
    thumbnailTextColor: "#ffffff",
    title: "dummy28",
  },
  {
    name: "dummy5",
    status: "hosted",
    thumbnailBgColor: "#898989",
    thumbnailTextColor: "#ffffff",
    title: "dummy29",
  },
  {
    name: "dummy5",
    status: "hosted",
    thumbnailBgColor: "#898989",
    thumbnailTextColor: "#ffffff",
    title: "dummy30",
  },
];

export default DUMMY_DATA;
